default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: blog_development
  username: dev
  password: root

test:
  <<: *default
  database: blog_development_test
  username: dev
  password: root

production:
  <<: *default
  database: blog_production
